[project]
name = "howie-assistant"
version = "0.1.0"
description = "A multimodal AI assistant for product knowledge."

[tool.setuptools.packages.find]
where = ["."]  # Look for packages in the current directory (the 'howie' root)
exclude = ["data*", "frontend*"]
